# Generated by Django 5.0.3 on 2024-03-25 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CfopCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cfop_com', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='CfopEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfop_com', models.CharField(max_length=4)),
                ('nome', models.CharField(max_length=70)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cfop.cfopentrada')),
            ],
        ),
    ]
